### ISSUE TITLE
Import not working on Windows, Python 3.4

### ISSUE THREAD

**Issue by elainethale** [vaidik/commentjson#3]
```
pip install commentjson
python
>>> import commentjson
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PyEnvs\3.4\lib\site-packages\commentjson\__init__.py", line 1, in <module>
    from commentjson import dump
ImportError: cannot import name 'dump'
>>>
```

**Comment by esafak** [comment]
It's not working in OS X either.

**Comment by haveaguess** [comment]
so this project is unsupported?

**Comment by gabyx** [comment]
jup please make it python3 compatible :-)

**Comment by zhanglongqi** [comment]
Can't work on Ubuntu16.04 either

**Comment by dominikandreas** [comment]
for those who need a quick and dirty fix:
copy everything from commentjson.py into __init__.py and it should work (commentjson.py is then no longer nessessary)

**Comment by derveit** [comment]
@dominikandreas Thanks for the workaround. Didn't work for me, though: 
"Phyton2.5.dll is missing on your computer". 

I'm using conda with Python 3.5.

**Comment by WindWang2** [comment]
@derveit @dominikandreas 's solution works for me. I use command 'mv commentjosn.py __init__.py'

**Comment by shandou** [comment]
As @WindWang2 described, pip install, then `cp commentjson.py __init__.py` is the first step to solve problem. I also need to change all the occurrence of `except Exception, e:` into `except Exception as e:` to finally make it work.

**Comment by johanneswilm** [comment]
Is there some replacement package for python3? Is @vaidik still alive? If not, has someone uploaded the fix under a different package name to pypi?

**Comment by yxandam** [comment]
delete all the text in __init__.py
 replaced with 
`import commentjson`
it will work.
good luck

**Comment by gabyx** [comment]
Why are you not making a pull request, instead of putting together the solution piece by piece .-) this will help other people too :-)

**Comment by johanneswilm** [comment]
@gabyx There are numerous PRs already. The maintainer has apparently just stopped responding to this. https://github.com/vaidik/commentjson/pulls

**Comment by gabyx** [comment]
there is already a pullrequest #15

**Comment by johanneswilm** [comment]
@gabyx Read the thread. :) JSON_minify [1] is where to switch.

[1] https://pypi.python.org/pypi/JSON_minify

**Comment by dubhe0215** [comment]
I solved the problem without `mv commentjson.py __init__.py`. I have just replaced all `from commentjson` with `from .commentjson` in `__init__.py`.

**Comment by vaidik** [comment]
Apologies, like I have in a few other threads. This should be working fine as of a few fixes back. I have added dedicated test runs for Windows now. And I am trying to be weekly active on the project.

Apologies once again for having disappeared.
